#!/usr/bin/env bash
# Pre-commit hook for harness
# 被 settings.json PreToolUse hook 调用
# 检测 git commit 时：
#   1. 验证 harness-state.json 已更新到今天
#   2. 自动补齐能补的 trace 文件（commands.log, diff.patch）
#   3. 检查剩余必填文件

# 读取 stdin JSON
INPUT=$(cat)

# 提取命令文本
COMMAND=$(echo "$INPUT" | grep -o '"command"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*: *"//;s/"$//')

# 不是 git commit → 放行
if [ -z "$COMMAND" ] || ! echo "$COMMAND" | grep -q "git commit"; then
  exit 0
fi

# 提取项目路径
PROJECT_PATH=$(echo "$INPUT" | grep -o '"cwd"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*: *"//;s/"$//')
if [ -z "$PROJECT_PATH" ]; then
  PROJECT_PATH="$(pwd)"
fi

STATE_FILE="$PROJECT_PATH/.claude/harness-state.json"
TODAY=$(date +%Y-%m-%d)

# 没有 harness-state.json → 非 harness 项目，放行
if [ ! -f "$STATE_FILE" ]; then
  exit 0
fi

# ============================================
# 检查 1: state 日期
# ============================================
if ! grep -q "\"date\": \"${TODAY}" "$STATE_FILE"; then
  LAST_DATE=$(grep -o '"date": "[0-9T:.-]*"' "$STATE_FILE" | head -1 | sed 's/"date": "//;s/"//')
  echo "╔══════════════════════════════════════════════════╗" >&2
  echo "║  ❌ harness-state.json 未更新 — 拦截 commit     ║" >&2
  echo "╚══════════════════════════════════════════════════╝" >&2
  echo "" >&2
  echo "last_execution.date = $LAST_DATE (不是今天 $TODAY)" >&2
  echo "先更新 harness-state.json 再 commit。" >&2
  exit 2
fi

# ============================================
# 检查 2: 找今天的 trace 目录
# ============================================
TRACE_BASE="$PROJECT_PATH/.claude/harness-lab/traces"
LATEST_DIR=$(find "$TRACE_BASE" -maxdepth 1 -type d -name "${TODAY}*" 2>/dev/null | sort | tail -1)

# 没有今天的 trace 目录 → state 更新了但没 trace，放行（可能是 trivial fix）
if [ -z "$LATEST_DIR" ]; then
  exit 0
fi

TRACE_REL=$(echo "$LATEST_DIR" | sed "s|$PROJECT_PATH/.claude/||")

# 检测任务类型：目录名包含 coding/audit → coding，
# 或者有 git diff 说明有代码改动 → coding
if echo "$TRACE_REL" | grep -qi "coding\|audit"; then
  TASK_TYPE="coding"
elif [ -n "$(cd "$PROJECT_PATH" && git diff --name-only HEAD~1 HEAD 2>/dev/null | grep -v '\.claude/' | head -1)" ]; then
  # 有非 .claude/ 的文件改动 → 编码任务
  TASK_TYPE="coding"
else
  TASK_TYPE="design"
fi

# ============================================
# 自动补齐: commands.log（编码/审计轮）
# ============================================
if [ "$TASK_TYPE" = "coding" ] && [ ! -f "$LATEST_DIR/commands.log" ]; then
  echo "[auto-fix] 生成 commands.log..." >&2
  COMMANDS_LOG="$LATEST_DIR/commands.log"
  echo "=== auto-generated by pre-commit hook ===" > "$COMMANDS_LOG"
  echo "date: $(date -Iseconds)" >> "$COMMANDS_LOG"
  echo "" >> "$COMMANDS_LOG"

  # 从 state 读取 commands 并执行
  # 提取 typecheck_*, build_*, smoke_* 命令
  while IFS= read -r line; do
    CMD_NAME=$(echo "$line" | grep -oP '"\K(typecheck_\w+|build_\w+|smoke_\w+)' 2>/dev/null || true)
    CMD_VALUE=$(echo "$line" | grep -oP ':\s*"\K[^"]+' 2>/dev/null || true)
    if [ -n "$CMD_NAME" ] && [ -n "$CMD_VALUE" ]; then
      echo "=== $CMD_NAME ===" >> "$COMMANDS_LOG"
      echo "\$ $CMD_VALUE" >> "$COMMANDS_LOG"
      OUTPUT=$(eval "$CMD_VALUE" 2>&1) || true
      echo "$OUTPUT" >> "$COMMANDS_LOG"
      echo "exit_code: $?" >> "$COMMANDS_LOG"
      echo "" >> "$COMMANDS_LOG"
    fi
  done < <(grep -E '"(typecheck_|build_|smoke_)' "$STATE_FILE" 2>/dev/null || true)

  if [ -s "$COMMANDS_LOG" ]; then
    echo "[auto-fix] commands.log 已生成 ($(wc -l < "$COMMANDS_LOG") lines)" >&2
  fi
fi

# ============================================
# 自动补齐: diff.patch（编码/审计轮）
# ============================================
if [ "$TASK_TYPE" = "coding" ]; then
  # 找 baseline commit（从 state 中的 last_execution 之前的 commit）
  BASELINE=$(cd "$PROJECT_PATH" && git log --format=%H --since="${TODAY}T00:00:00" --reverse 2>/dev/null | head -1)
  if [ -z "$BASELINE" ]; then
    BASELINE=$(cd "$PROJECT_PATH" && git log --format=%H -2 2>/dev/null | tail -1)
  fi

  if [ -n "$BASELINE" ]; then
    # 为每个有 result.md 但没有 diff.patch 的 worker 生成 diff
    for result_file in "$LATEST_DIR"/worker-*-result.md; do
      [ -f "$result_file" ] || continue
      WORKER_N=$(echo "$result_file" | grep -o 'worker-[0-9]*' | grep -o '[0-9]*')
      DIFF_FILE="$LATEST_DIR/worker-${WORKER_N}-diff.patch"

      if [ ! -f "$DIFF_FILE" ]; then
        echo "[auto-fix] 生成 worker-${WORKER_N}-diff.patch..." >&2
        {
          echo "=== worker-${WORKER_N} diff (auto-generated) ==="
          echo "baseline: $BASELINE"
          echo ""
          cd "$PROJECT_PATH" && git diff --stat "$BASELINE" HEAD 2>&1 || true
          echo ""
          cd "$PROJECT_PATH" && git diff "$BASELINE" HEAD 2>&1 || true
        } > "$DIFF_FILE"
        echo "[auto-fix] worker-${WORKER_N}-diff.patch 已生成" >&2
      fi
    done
  fi
fi

# ============================================
# 最终检查: 必填文件
# ============================================
ERRORS=0

# scorecard + verification（必填）
for file in verification.md scorecard.json; do
  if [ ! -f "$LATEST_DIR/$file" ]; then
    echo "FAIL: $file 缺失" >&2
    ERRORS=$((ERRORS + 1))
  fi
done

# result.md（必填）
for result_file in "$LATEST_DIR"/worker-*-result.md; do
  [ -f "$result_file" ] && break
  echo "FAIL: 无任何 worker result.md" >&2
  ERRORS=$((ERRORS + 1))
  break
done

# prompt.md → 降级为警告（Coordinator 手写不可靠，不阻塞 commit）
PROMPT_COUNT=$(ls "$LATEST_DIR"/worker-*-prompt.md 2>/dev/null | wc -l)
RESULT_COUNT=$(ls "$LATEST_DIR"/worker-*-result.md 2>/dev/null | wc -l)
if [ "$PROMPT_COUNT" -lt "$RESULT_COUNT" ]; then
  echo "WARN: prompt.md 缺失 ($PROMPT_COUNT/$RESULT_COUNT)（不阻塞 commit，但影响 trace 完整性）" >&2
fi

# scorecard composite_score
if [ -f "$LATEST_DIR/scorecard.json" ]; then
  if ! grep -q '"composite_score"' "$LATEST_DIR/scorecard.json"; then
    echo "FAIL: scorecard.json 缺少 composite_score" >&2
    ERRORS=$((ERRORS + 1))
  fi
fi

if [ $ERRORS -eq 0 ]; then
  echo "╔══════════════════════════════════════════╗" >&2
  echo "║  ✅ Harness check passed — commit 放行   ║" >&2
  echo "╚══════════════════════════════════════════╝" >&2
  exit 0
else
  echo "╔══════════════════════════════════════════════════╗" >&2
  echo "║  ❌ $ERRORS 项必填检查失败 — 拦截 commit         ║" >&2
  echo "╚══════════════════════════════════════════════════╝" >&2
  exit 2
fi
